
/*
 * CreateGistDialog.java
 *
 * Created on 3.6.2011, 21:21:51
 */
package cz.inseo.netbeans.github.gist;

import cz.inseo.netbeans.github.GitHubAuth;
import cz.inseo.netbeans.github.options.GitHubOptions;
import java.awt.Cursor;
import java.awt.Point;
import java.io.IOException;
import java.util.Collections;
import javax.swing.SwingUtilities;
import org.eclipse.egit.github.core.Gist;
import org.eclipse.egit.github.core.GistFile;
import org.eclipse.egit.github.core.client.RequestException;
import org.openide.util.Exceptions;
import org.openide.util.RequestProcessor;

/**
 *
 * @author Pavel
 */
public class CreateGistDialog extends java.awt.Dialog {

	/** Creates new form CreateGistDialog */
	public CreateGistDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		loadSetting();
	}

	private void loadSetting() {
		String login = GitHubOptions.getInstance().getLogin();

		if (login != null && !login.equals("")) {
			logedRadio.setVisible(true);
			logedRadio.setText(login);
			logedRadio.setSelected(true);
		} else {
			logedRadio.setEnabled(false);
			logedRadio.setVisible(false);
			anonymousRadio.setSelected(true);
		}
	}

	public void setFile(String fileName, String content, String mimeType) {
		fileNameText.setText(fileName);
		editorPane.setContentType(mimeType);
		editorPane.setText(content);
	}

	private Gist buildGist() {
		Gist gist = new Gist();
		gist.setDescription(descriptionText.getText());
		if (logedRadio.isSelected()) {
			//	gist.setUser(GitHubAuth.getUserService());
		}

		GistFile file = new GistFile().setContent(editorPane.getText());
		gist.setFiles(Collections.singletonMap(fileNameText.getText(), file));

		return gist;
	}

	private void createdDialog(final String url) {
		final Point m_location = getLocation();
		RequestProcessor.getDefault().execute(new Runnable() {

			@Override
			public void run() {

				SwingUtilities.invokeLater(new Runnable() {

					@Override
					public void run() {
						CreatedDialog createdDialog = new CreatedDialog(null, true);
						createdDialog.urlText.setText(url);
						createdDialog.setLocation(m_location);						
						createdDialog.setFocusableWindowState(true);
						createdDialog.setVisible(true);
					}
				});
			}
		});
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userRadioGroup = new javax.swing.ButtonGroup();
        dialogPane = new javax.swing.JPanel();
        filePane = new javax.swing.JPanel();
        fileNameText = new javax.swing.JTextField();
        fileNameLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        logedRadio = new javax.swing.JRadioButton();
        anonymousRadio = new javax.swing.JRadioButton();
        fileScrollPane = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();
        createPrivateButton = new javax.swing.JButton();
        addFileButton = new javax.swing.JButton();
        createPublicButton = new javax.swing.JButton();
        descriptionPane = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        descriptionText = new javax.swing.JTextField();
        descriptionSeparator = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(720, 510));
        setTitle(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        fileNameLabel.setText(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.fileNameLabel.text")); // NOI18N

        userLabel.setText(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.userLabel.text")); // NOI18N

        userRadioGroup.add(logedRadio);
        logedRadio.setText(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.logedRadio.text")); // NOI18N

        userRadioGroup.add(anonymousRadio);
        anonymousRadio.setSelected(true);
        anonymousRadio.setText(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.anonymousRadio.text")); // NOI18N

        editorPane.setText(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.editorPane.text")); // NOI18N
        fileScrollPane.setViewportView(editorPane);

        createPrivateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/inseo/netbeans/github/resources/images/private.png"))); // NOI18N
        createPrivateButton.setText(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.createPrivateButton.text")); // NOI18N
        createPrivateButton.setIconTextGap(8);
        createPrivateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPrivateButtonActionPerformed(evt);
            }
        });

        addFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/inseo/netbeans/github/resources/images/new_file.png"))); // NOI18N
        addFileButton.setText(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.addFileButton.text")); // NOI18N
        addFileButton.setEnabled(false);
        addFileButton.setIconTextGap(8);
        addFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileButtonActionPerformed(evt);
            }
        });

        createPublicButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/inseo/netbeans/github/resources/images/public.png"))); // NOI18N
        createPublicButton.setText(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.createPublicButton.text")); // NOI18N
        createPublicButton.setIconTextGap(8);
        createPublicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPublicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filePaneLayout = new javax.swing.GroupLayout(filePane);
        filePane.setLayout(filePaneLayout);
        filePaneLayout.setHorizontalGroup(
            filePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, filePaneLayout.createSequentialGroup()
                        .addGroup(filePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fileNameLabel)
                            .addComponent(userLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(filePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(filePaneLayout.createSequentialGroup()
                                .addComponent(anonymousRadio)
                                .addGap(18, 18, 18)
                                .addComponent(logedRadio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE))
                    .addGroup(filePaneLayout.createSequentialGroup()
                        .addComponent(addFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addComponent(createPrivateButton)
                        .addGap(18, 18, 18)
                        .addComponent(createPublicButton))
                    .addComponent(fileScrollPane, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        filePaneLayout.setVerticalGroup(
            filePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameLabel)
                    .addComponent(fileNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(anonymousRadio)
                    .addComponent(logedRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createPublicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createPrivateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        descriptionLabel.setText(org.openide.util.NbBundle.getMessage(CreateGistDialog.class, "CreateGistDialog.descriptionLabel.text")); // NOI18N

        javax.swing.GroupLayout descriptionPaneLayout = new javax.swing.GroupLayout(descriptionPane);
        descriptionPane.setLayout(descriptionPaneLayout);
        descriptionPaneLayout.setHorizontalGroup(
            descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addComponent(descriptionSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        descriptionPaneLayout.setVerticalGroup(
            descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(descriptionSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout dialogPaneLayout = new javax.swing.GroupLayout(dialogPane);
        dialogPane.setLayout(dialogPaneLayout);
        dialogPaneLayout.setHorizontalGroup(
            dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dialogPaneLayout.createSequentialGroup()
                .addComponent(filePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialogPaneLayout.setVerticalGroup(
            dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(dialogPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		setVisible(false);
		dispose();
    }//GEN-LAST:event_closeDialog

	private void createPrivateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPrivateButtonActionPerformed
		Gist gist = buildGist();
		gist.setPublic(false);
		try {
			setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
			Gist createGist = GitHubAuth.getGistService(!anonymousRadio.isSelected()).createGist(gist);
			createdDialog(createGist.getHtmlUrl());
			closeDialog(null);
		} catch (RequestException ex) {
			GitHubAuth.processException(ex);
		} catch (IOException ex) {
			Exceptions.printStackTrace(ex);
		}finally{
			setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
		}
}//GEN-LAST:event_createPrivateButtonActionPerformed

	private void addFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileButtonActionPerformed
		//Gist gist = buildGist();
		//add to explorer & close
}//GEN-LAST:event_addFileButtonActionPerformed

	private void createPublicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPublicButtonActionPerformed
		Gist gist = buildGist();
		gist.setPublic(true);
		try {
			setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
			Gist createGist = GitHubAuth.getGistService(!anonymousRadio.isSelected()).createGist(gist);
			createdDialog(createGist.getHtmlUrl());
			closeDialog(null);
		} catch (RequestException ex) {
			GitHubAuth.processException(ex);
		} catch (IOException ex) {
			Exceptions.printStackTrace(ex);
		}finally{
			setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
		}
}//GEN-LAST:event_createPublicButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				CreateGistDialog dialog = new CreateGistDialog(new java.awt.Frame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileButton;
    private javax.swing.JRadioButton anonymousRadio;
    private javax.swing.JButton createPrivateButton;
    private javax.swing.JButton createPublicButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel descriptionPane;
    private javax.swing.JSeparator descriptionSeparator;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JPanel dialogPane;
    private javax.swing.JEditorPane editorPane;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JTextField fileNameText;
    private javax.swing.JPanel filePane;
    private javax.swing.JScrollPane fileScrollPane;
    private javax.swing.JRadioButton logedRadio;
    private javax.swing.JLabel userLabel;
    private javax.swing.ButtonGroup userRadioGroup;
    // End of variables declaration//GEN-END:variables
}
