package cz.inseo.netbeans.github.gist;

import cz.inseo.netbeans.github.gist.tree.RootNode;
import cz.inseo.netbeans.github.gist.tree.GistChildren;
import cz.inseo.netbeans.github.options.GithubOptions;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//cz.inseo.netbeans.github.gist//Gists//EN",
autostore = false)
@TopComponent.Description(preferredID = "GistsTopComponent",
iconBase="cz/inseo/netbeans/github/resources/images/g-icon.png", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "cz.inseo.netbeans.github.gist.GistsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_GistsAction",
preferredID = "GistsTopComponent")
public final class GistsTopComponent extends TopComponent implements ExplorerManager.Provider {

	private transient ExplorerManager explorerManager = new ExplorerManager();

	public GistsTopComponent() {
		initComponents();
		initExplorerManager();
		setName(NbBundle.getMessage(GistsTopComponent.class, "CTL_GistsTopComponent"));
		setToolTipText(NbBundle.getMessage(GistsTopComponent.class, "HINT_GistsTopComponent"));		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gistsPane = new BeanTreeView();

        setLayout(new java.awt.BorderLayout());
        add(gistsPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane gistsPane;
    // End of variables declaration//GEN-END:variables

	@Override
	public void componentOpened() {
		// TODO add custom code on component opening
	}

	@Override
	public void componentClosed() {
		// TODO add custom code on component closing
	}

	void writeProperties(java.util.Properties p) {
		// better to version settings since initial version as advocated at
		// http://wiki.apidesign.org/wiki/PropertyFiles
		p.setProperty("version", "1.0");
		// TODO store your settings
	}

	void readProperties(java.util.Properties p) {
		String version = p.getProperty("version");
		// TODO read your settings according to their version
	}

	@Override
	public ExplorerManager getExplorerManager() {
		return explorerManager;
	}
	
	private void initExplorerManager(){
		associateLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()));
		String userName = GithubOptions.getInstance().getLogin();
		explorerManager.setRootContext(new RootNode(new GistChildren(userName)));
		explorerManager.getRootContext().setDisplayName(userName+"'s Gists");
	}
}
